# Generated by Django 2.1.1 on 2018-09-19 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0005_auto_20180919_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_add', models.BooleanField(default=False, verbose_name='投诉新增功能')),
                ('cpt_delete', models.BooleanField(default=False, verbose_name='投诉删除功能')),
                ('cpt_edit', models.BooleanField(default=False, verbose_name='投诉编辑功能')),
                ('driver_add', models.BooleanField(default=False, verbose_name='司机新增功能')),
                ('driver_delete', models.BooleanField(default=False, verbose_name='司机删除功能')),
                ('driver_edit', models.BooleanField(default=False, verbose_name='投诉编辑功能')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='driver.Department', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
    ]
