# Generated by Django 2.1.1 on 2018-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户权限', 'verbose_name_plural': '用户权限'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='driver_edit',
            field=models.BooleanField(default=False, verbose_name='司机编辑功能'),
        ),
    ]
