# Generated by Django 2.1.1 on 2018-09-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Dirver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='司机姓名')),
                ('work_number', models.CharField(max_length=10, unique=True, verbose_name='上岗证号')),
                ('car_number', models.CharField(max_length=10, verbose_name='车牌号码')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式')),
                ('scheduling', models.CharField(blank=True, choices=[('1', '白班'), ('2', '夜班'), ('3', '顶班'), ('4', '其他')], max_length=50, null=True, verbose_name='值班情况')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='交班地点')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='driver.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '司机列表',
                'verbose_name_plural': '司机列表',
            },
            managers=[
                ('driver', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('image', models.ImageField(blank=True, upload_to='user/%Y/%m/%d', verbose_name='头像')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='driver.Department', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
