# Generated by Django 2.1.1 on 2018-09-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dirver',
            new_name='Driver',
        ),
    ]
