# Generated by Django 2.1.1 on 2018-09-15 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20180914_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='driver.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='scheduling',
            field=models.CharField(blank=True, choices=[('1', '白班'), ('2', '夜班'), ('3', '顶班')], max_length=50, null=True, verbose_name='值班情况'),
        ),
    ]
