# Generated by Django 2.1.1 on 2018-09-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20180915_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complaint_add_editable',
            field=models.BooleanField(default=False, verbose_name='投诉新增编辑'),
        ),
        migrations.AddField(
            model_name='profile',
            name='complaint_delete_editable',
            field=models.BooleanField(default=False, verbose_name='投诉删除编辑'),
        ),
    ]
