# Generated by Django 2.1.1 on 2018-09-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20180919_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
