# Generated by Django 2.1.1 on 2018-09-14 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('complaint_number', models.CharField(default='20180914215410813', max_length=20, unique=True, verbose_name='投诉编号')),
                ('category', models.CharField(choices=[('1', '投诉'), ('2', '失物查找'), ('3', '其他')], default='1', max_length=50, verbose_name='类型')),
                ('record_date', models.DateTimeField(verbose_name='登记日期')),
                ('happen_date', models.DateTimeField(verbose_name='事发日期')),
                ('complainant', models.CharField(max_length=20, verbose_name='投诉人')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='投诉人联系方式')),
                ('content', models.TextField(blank=True, null=True, verbose_name='投诉内容')),
                ('feedback_content', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('is_finished', models.BooleanField(default=False, verbose_name='处理进度')),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='司机姓名')),
                ('driver_work_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务监督号')),
                ('driver_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_user', to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '投诉列表',
                'verbose_name_plural': '投诉列表',
            },
        ),
    ]
