# Generated by Django 2.1.1 on 2018-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(default='20180914215625690', max_length=20, unique=True, verbose_name='投诉编号'),
        ),
    ]
