# Generated by Django 2.1.1 on 2018-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20180914_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(default='20180914221046084', max_length=20, unique=True, verbose_name='投诉编号'),
        ),
    ]
