# Generated by Django 2.1.1 on 2018-09-16 14:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20180915_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(default='20180916221905541', max_length=20, unique=True, verbose_name='投诉编号'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='投诉内容'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='feedback_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='处理结果'),
        ),
    ]
