# Generated by Django 2.1.1 on 2018-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20180916_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(default='20180917143107563', max_length=20, unique=True, verbose_name='投诉编号'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='投诉内容'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='feedback_content',
            field=models.TextField(blank=True, null=True, verbose_name='处理结果'),
        ),
    ]
