# Generated by Django 2.1.1 on 2018-09-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_auto_20180917_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='附件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(default='20180918084615270', max_length=20, unique=True, verbose_name='投诉编号'),
        ),
    ]
