# Generated by Django 2.1.1 on 2018-09-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_auto_20180919_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(default='20180919131551527', max_length=20, unique=True, verbose_name='投诉编号'),
        ),
    ]
