# Generated by Django 2.1.1 on 2018-09-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_auto_20180919_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(default='20180919144145015', max_length=20, unique=True, verbose_name='投诉编号'),
        ),
    ]
